const sampleInfos = [
    {
        gpNum: 1,
        name: 'Wallie',
        rollNum: 2,
        
        effort1: 1,
        effort2: 3,
        effort3: 4,
        effort4: 0,
        effort5: 1,
        effort6: 4,
        effort7: 2,
        effort8: 0,
        effort9: 1,
        effort10: 4,
        effort11: 4,
        effort12: 3,
        
    },
    {
        gpNum: 1,
        name: 'Alice',
        rollNum: 20,
        effort1: 3, 
        effort2: 4, 
        effort3: 2, 
        effort4: 1, 
        effort5: 4, 
        effort6: 0, 
        effort7: 3, 
        effort8: 2, 
        effort9: 1, 
        effort10: 4, 
        effort11: 3,
        effort12: 0 
        
    },
    {
        gpNum: 1,
        name: 'Carol',
        rollNum: 98,
        
        effort1: 2,
        effort2: 1, 
        effort3: 3, 
        effort4: 0, 
        effort5: 4, 
        effort6: 2, 
        effort7: 1, 
        effort8: 4, 
        effort9: 3, 
        effort10: 0,
        effort11: 2, 
        effort12: 1
        
    },
    {
        gpNum: 2,
        name: "Jane Smith",
        rollNum: 102,
        effort1: 4, 
        effort2: 3, 
        effort3: 1, 
        effort4: 2, 
        effort5: 0, 
        effort6: 3, 
        effort7: 4,
        effort8: 1,
        effort9: 2,
        effort10: 0,
        effort11: 4,
        effort12: 3,
    },
    {
        gpNum: 3,
        name: "Bob Johnson",
        rollNum: 103,
        effort1: 1,
        effort2: 2,
        effort3: 4,
        effort4: 3, 
        effort5: 0, 
        effort6: 1, 
        effort7: 2, 
        effort8: 3, 
        effort9: 4,
        effort10: 0,
        effort11: 3,
        effort12: 2 
    },
    {
        gpNum: 4,
        name: "Alice Williams",
        rollNum: 104,
        effort1: 3, 
        effort2: 4, 
        effort3: 2, 
        effort4: 1, 
        effort5: 0, 
        effort6: 2, 
        effort7: 3, 
        effort8: 4, 
        effort9: 1, 
        effort10: 4, 
        effort11: 2, 
        effort12: 0 
    },
    {
        gpNum: 5,
        name: "Bob",
        rollNum: 16,
        effort1: 0, 
        effort2: 1,
        effort3: 3, 
        effort4: 4, 
        effort5: 2, 
        effort6: 1, 
        effort7: 2, 
        effort8: 0, 
        effort9: 4, 
        effort10: 3, 
        effort11: 2, 
        effort12: 1 
    },
    {
        gpNum: 5,
        name: "John",
        rollNum: 7,
        
        effort1: 4, 
        effort2: 3,
        effort3: 1, 
        effort4: 2, 
        effort5: 0, 
        effort6: 3, 
        effort7: 4,
        effort8: 1,
        effort9: 2,
        effort10: 0,
        effort11: 4, 
        effort12: 3 
        
    },
    {
        gpNum: 5,
        name: "Marley",
        rollNum: 6,
        effort1: 0,
        effort2: 2,
        effort3: 1,
        effort4: 4,
        effort5: 2,
        effort6: 0,
        effort7: 2,
        effort8: 1,
        effort9: 3,
        effort10: 1,
        effort11: 3,
        effort12: 2,
    },
    {
        gpNum: 6,
        name: "Bobby",
        rollNum: 9,
        effort1: 1, 
        effort2: 2, 
        effort3: 4, 
        effort4: 3, 
        effort5: 0, 
        effort6: 1, 
        effort7: 2, 
        effort8: 3, 
        effort9: 4, 
        effort10: 0, 
        effort11: 3, 
        effort12: 2 
    },
];

module.exports = {data: sampleInfos};